name: Build on Raspberry Pi

on:
  push:
    branches:
      - workflow-test
#    tags:
#      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH for private submodules
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up QEMU for ARM builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake autoconf libudev-dev automake autoconf-archive ninja-build gcc g++

      - name: Set VCPKG Environment Variable
        run: echo "VCPKG_FORCE_SYSTEM_BINARIES=1" >> $GITHUB_ENV

      - name: Set Compiler Variables
        run: |
          echo "CC=gcc" >> $GITHUB_ENV
          echo "CXX=g++" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja -DCMAKE_MAKE_PROGRAM=ninja

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MiniOmni-RPi-Build
          path: build/MiniOmni
