name: Build on Raspberry Pi

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up QEMU for ARM builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake autoconf libudev-dev automake autoconf-archive

      - name: Set VCPKG Environment Variable
        run: echo "VCPKG_FORCE_SYSTEM_BINARIES=1" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Build Project
        run: |
          cd build
          cmake --build . --config Release

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MiniOmni-RPi-Build
          path: build/MiniOmni
